-- Arabic URL Shortener schema (UTF8MB4) v4 (users + subscriptions)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NULL UNIQUE,
  pass_hash VARCHAR(255) NULL,
  oauth_provider VARCHAR(50) NULL,
  oauth_id VARCHAR(255) NULL,
  is_paid TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

CREATE TABLE IF NOT EXISTS links (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  slug VARCHAR(64) NOT NULL UNIQUE,
  long_url TEXT NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  is_paid TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator_ip VARBINARY(16) NULL,
  clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_click TIMESTAMP NULL,
  CONSTRAINT chk_slug CHECK (CHAR_LENGTH(slug) BETWEEN 3 AND 64),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

CREATE INDEX idx_creator_ip ON links (creator_ip);

CREATE TABLE IF NOT EXISTS clicks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  link_id BIGINT UNSIGNED NOT NULL,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ua VARCHAR(255) NULL,
  referer TEXT NULL,
  ip VARBINARY(16) NULL,
  FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Admin users table (hashed passwords) (kept for site admin)
CREATE TABLE IF NOT EXISTS admin_users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  pass_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

-- Login attempts for throttling (admin)
CREATE TABLE IF NOT EXISTS login_attempts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NULL,
  ip VARBINARY(16) NULL,
  attempted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  success TINYINT(1) NOT NULL DEFAULT 0
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
